stages:
  load_data:
    cmd: python src/load_data.py --congig=params.yaml
    deps:
      - src/get_data.py
      - src/load_data.py
      - source_data/med-insurance.csv

    outs:
      - data/raw/insurance.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - src/split_data.py
      - data/raw/insurance.py

    outs:
      - data/processed/train_insurance.csv
      - data/processed/test_insurance.csv
       

