channels:
- conda-forge
dependencies:
- python=3.11.6
- pip<=24.1.2
- pip:
  - mlflow==2.14.2
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==24.1
  - psutil==6.0.0
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.14.0
name: mlflow-env
