name: Expenses

on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: [ ubuntu-latest ]  #self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set Up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements_docker.txt ]; then pip install -r requirements_docker.txt; fi

      - name: Docker Build and Push to Docker Hub
        run: |
         docker build -t medical .
         docker tag medical xerxez786/medical:latest
         docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{ secrets.DOCKERHUB_TOKEN }}
         docker push xerxez786/medical:latest
        env:
          DOCKER_CLI_ACI: 1

      - name: Lint with flake8
        run: |
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Build and Anlyze the SonarQube
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Trivy Files System
        run : trivy fs . > trivy.txt

      - name: Image Scan
        run : trivy image xerxez786/medical:latest > trivyimage.txt

      - name: Trivy CIS Compliance Issue
        run: trivy image --compliance docker-cis xerxez786/medical:latest > trivycompliance.txt


