name: Expenses

on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: [ ubuntu-latest ]  #self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set Up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements_docker.txt ]; then pip install -r requirements_docker.txt; fi

